stages:
  - deploy

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - "ui/**" 
        - "server/**" 
        - "index.html" 
        - "main.js"
      when: on_success
    - when: never
